//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities3 : DbContext
    {
        public Entities3()
            : base("name=Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Авторизация> Авторизация { get; set; }
        public virtual DbSet<ВторникН> ВторникН { get; set; }
        public virtual DbSet<ВторникС> ВторникС { get; set; }
        public virtual DbSet<ВторникСТ> ВторникСТ { get; set; }
        public virtual DbSet<Начальный_класс> Начальный_класс { get; set; }
        public virtual DbSet<ПонедельникН> ПонедельникН { get; set; }
        public virtual DbSet<ПонедельникС> ПонедельникС { get; set; }
        public virtual DbSet<ПонедельникСТ> ПонедельникСТ { get; set; }
        public virtual DbSet<Постоянное> Постоянное { get; set; }
        public virtual DbSet<Предмет1> Предмет1 { get; set; }
        public virtual DbSet<ПятницаН> ПятницаН { get; set; }
        public virtual DbSet<ПятницаС> ПятницаС { get; set; }
        public virtual DbSet<ПятницаСТ> ПятницаСТ { get; set; }
        public virtual DbSet<СредаН> СредаН { get; set; }
        public virtual DbSet<СредаС> СредаС { get; set; }
        public virtual DbSet<СредаСТ> СредаСТ { get; set; }
        public virtual DbSet<Средний_класс> Средний_класс { get; set; }
        public virtual DbSet<Старший_класс> Старший_класс { get; set; }
        public virtual DbSet<ЧетвергН> ЧетвергН { get; set; }
        public virtual DbSet<ЧетвергС> ЧетвергС { get; set; }
        public virtual DbSet<ЧетвергСТ> ЧетвергСТ { get; set; }
    }
}
