//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Авторизация
    {
        public int ID_Пользователя { get; set; }
        public string Фио { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Префикс { get; set; }
    }
}
