//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Начальный_класс
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Начальный_класс()
        {
            this.Постоянное = new HashSet<Постоянное>();
        }
    
        public int ID_Начальный_Класс { get; set; }
        public int Понедельник { get; set; }
        public int Вторник { get; set; }
        public int Среда { get; set; }
        public int Четверг { get; set; }
        public int Пятница { get; set; }
    
        public virtual ВторникН ВторникН { get; set; }
        public virtual ПонедельникН ПонедельникН { get; set; }
        public virtual ПятницаН ПятницаН { get; set; }
        public virtual СредаН СредаН { get; set; }
        public virtual ЧетвергН ЧетвергН { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Постоянное> Постоянное { get; set; }
    }
}
