//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Средний_класс
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Средний_класс()
        {
            this.Постоянное = new HashSet<Постоянное>();
        }
    
        public int ID_Средний_Класс { get; set; }
        public int Понедельник { get; set; }
        public int Вторник { get; set; }
        public int Среда { get; set; }
        public int Четверг { get; set; }
        public int Пятница { get; set; }
    
        public virtual ВторникС ВторникС { get; set; }
        public virtual ПонедельникС ПонедельникС { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Постоянное> Постоянное { get; set; }
        public virtual ПятницаС ПятницаС { get; set; }
        public virtual СредаС СредаС { get; set; }
        public virtual ЧетвергС ЧетвергС { get; set; }
    }
}
