//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Старший_класс
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Старший_класс()
        {
            this.Постоянное = new HashSet<Постоянное>();
        }
    
        public int ID_Старший_Класс { get; set; }
        public int Понедельник { get; set; }
        public int Вторник { get; set; }
        public int Среда { get; set; }
        public int Четверг { get; set; }
        public int Пятница { get; set; }
    
        public virtual ВторникСТ ВторникСТ { get; set; }
        public virtual ПонедельникСТ ПонедельникСТ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Постоянное> Постоянное { get; set; }
        public virtual ПятницаСТ ПятницаСТ { get; set; }
        public virtual СредаСТ СредаСТ { get; set; }
        public virtual ЧетвергСТ ЧетвергСТ { get; set; }
    }
}
